services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=BabaStrongPassword123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"  
    volumes:
      - my_sql_data:/var/opt/mssql  

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data


      #  mongo:
 #    container_name: mongo_container
 #    environment:
 #      - MONGO_URI=mongodb+srv://babastrong:babastrongpassword123@cluster0.jwndv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
 
 #mongo db atlas uzerinden yonetiliyor þimdilik


volumes:
  my_sql_data:
    driver: local
  redis_data:
    driver: local
