services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=BabaStrongPassword123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"  
    volumes:
      - my_sql_data:/var/opt/mssql  
volumes:
  my_sql_data:
    driver: local
